### ISSUE TITLE
Unable to run app.js

### ISSUE THREAD

**Issue by effello** [mathiask88/node-snap7-testsuite#1] opened 2015-03-23 08:52 UTC
Hi, iwas trying to open the Project in WebStorm IDE and tried to run or debug it, because i want to complete it an maybe port it to a Mean Stack and build some Kind of Viriable Store for the Data comming from the S7. But I only got this error.

/usr/bin/node working/app.js

/data/Projekte/nodejs/node-snap7-testsuite/working/node_modules/node-snap7/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /data/Projekte/nodejs/node-snap7-testsuite/working/node_modules/node-snap7/build/Release/node_snap7.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/data/Projekte/nodejs/node-snap7-testsuite/working/node_modules/node-snap7/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/data/Projekte/nodejs/node-snap7-testsuite/working/node_modules/node-snap7/lib/node-snap7.js:6:45)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Process finished with exit code 8

Do you have a clou where it mieght come from

**Comment by mathiask88** [comment] 2015-03-23 12:53
Hi, I will have a look this evening and push an update.

**Comment by mathiask88** [comment] 2015-03-23 18:39
@effello I updated dependencies and it should run now under node `v0.10.x`. `0.12` and `iojs` are not yet supported by socket.io (there is a hotfix).

**Comment by effello** [comment] 2015-03-24 08:22
nice that you changed so fast, but that was not the problem for me. At the point in socketEvents.js where you require node-snap7 it crashes. ???

**Comment by mathiask88** [comment] 2015-03-24 08:25
I cant reproduce that. What's your os/node version?  Did you try a fresh `npm install` or `npm rebuild`?

**Comment by effello** [comment] 2015-03-24 08:32
Hi,
my OS is Ubunutu 14.10 Node version is v0.12.0 Made a fresh git clone 
and npm install just minutes ago the Problem I saw it only Happens in 
the WebStorm IDE if I start it from CommandLine it is working but I can 
not debug and dont know why I can't See anything as a response to a read 
Opreration it doesnt create a Buffer becuase data.length is always 
undefined.

On 24.03.2015 09:25, Mathias Küsel wrote:

> I cant reproduce that. What's your os/node version? Did you try a 
> fresh |npm install| or |npm rebuild|?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mathiask88/node-snap7-testsuite/issues/1#issuecomment-85393625.

## 

Hoeffken IT
Florian Höffken
Rhoendorfer Strasse 61
53604 Bad Honnef
tel: +492224900451

**Comment by mathiask88** [comment] 2015-03-24 08:40
on 0.12 i saw a slightly different behaviour from socket.io responses. try to add a line `data = data.data;` in `dataRW.jade` in `onData` before `createBufferTable(...)`

**Comment by effello** [comment] 2015-03-24 08:47
nice thats it! Maybe the other Problem has something to with the binding 
stuff or WebStorm itself but I cant debug server things and do you know 
how to debug stuff working in jade templates because I can not see them 
in developer tools of chrome?

On 24.03.2015 09:40, Mathias Küsel wrote:

> |data = data.data|

## 

Hoeffken IT
Florian Höffken
Rhoendorfer Strasse 61
53604 Bad Honnef
tel: +492224900451

**Comment by effello** [comment] 2015-03-24 08:50
It also is not only happening in the testsuite. I can see the same error 
in node-snap7

On 24.03.2015 09:40, Mathias Küsel wrote:

> |data = data.data|

## 

Hoeffken IT
Florian Höffken
Rhoendorfer Strasse 61
53604 Bad Honnef
tel: +492224900451

**Comment by mathiask88** [comment] 2015-03-24 09:01
If it works in console then I think it is a webstorm issue. Seems that the addon is build against another node version.

**Comment by effello** [comment] 2015-03-24 10:18
Yes you where right everything working now thank you.
I hope i can add something to work now...

Thanks a lot great Work!
Greetz

On 24.03.2015 10:01, Mathias Küsel wrote:

> If it works in console then I think it is a webstorm issue. Seems that 
> the addon is build against another node version.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mathiask88/node-snap7-testsuite/issues/1#issuecomment-85410101.

## 

Hoeffken IT
Florian Höffken
Rhoendorfer Strasse 61
53604 Bad Honnef
tel: +492224900451

**Comment by mathiask88** [comment] 2015-03-24 10:25
Nice, PRs are welcome ;)

**Comment by mathiask88** [comment] 2015-09-14 19:47
fixed in https://github.com/mathiask88/node-snap7-testsuite/commit/68a8f6b3515be44e9ea22a68c8cd4313eb4a2b44

**Closed as completed by mathiask88** 2015-09-14 19:47 UTC
